version: '3.9'

services:
  tortracker-backend:
    image: tortracker:backend
    ports:
      - "3001:3001"
    volumes:
      - tortracker/tortracker.db:/app/tortracker.db

  tortracker-frontend:
    image: tortracker:frontend
    ports:
      - "3000:3000"
