version: '3.9'

services:
  tortracker-backend:
    image: tortracker:backend
    ports:
      - "3001:3001"
    restart: always
    logging:
      driver: none

  tortracker-frontend:
    image: tortracker:frontend
    ports:
      - "3000:3000"
    restart: always
    logging:
      driver: none
